# Generated by Django 5.2 on 2025-04-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0005_alter_contactmessage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.product')),
            ],
        ),
    ]
