# Generated by Django 5.2 on 2025-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='timestamp',
        ),
    ]
